#ifndef SYSTEMATIC_DEFS_HH
#define SYSTEMATIC_DEFS_HH
namespace syst
{
  enum Systematic {
    NONE, BUP, BDOWN, CUP, CDOWN, UUP, UDOWN, TUP, TDOWN, ELUP, ELDOWN,
    MUUP, MUDOWN, LEPTRIGUP, LEPTRIGDOWN, PUUP, PUDOWN
  };
};

#endif
